clients:
  - url: http://172.16.9.116:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: my-golang-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: myapp
          __path__: /var/log/*.log
